# docs:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@emotion/react"
      - dependency-name: "@emotion/styled"
      - dependency-name: "@fontsource/roboto"
      - dependency-name: "@fortawesome/fontawesome-svg-core"
      - dependency-name: "@fortawesome/free-brands-svg-icons"
      - dependency-name: "@fortawesome/free-solid-svg-icons"
      - dependency-name: "@fortawesome/react-fontawesome"
      - dependency-name: "@mui/icons-material"
      - dependency-name: "@mui/lab"
      - dependency-name: "@mui/material"
      - dependency-name: "@react-oauth/google"
      - dependency-name: "@reduxjs/toolkit"
      - dependency-name: "@tiptap/extension-highlight"
      - dependency-name: "@tiptap/extension-link"
      - dependency-name: "@tiptap/extension-placeholder"
      - dependency-name: "@tiptap/extension-text-align"
      - dependency-name: "@tiptap/extension-underline"
      - dependency-name: "@tiptap/pm"
      - dependency-name: "@tiptap/react"
      - dependency-name: "@tiptap/starter-kit"
      - dependency-name: "@types/react-color"
      - dependency-name: "@xyflow/react"
      - dependency-name: "ace-builds"
      - dependency-name: "axios"
      - dependency-name: "dompurify"
      - dependency-name: "driver.js"
      - dependency-name: "elkjs"
      - dependency-name: "eta"
      - dependency-name: "fuse.js"
      - dependency-name: "handlebars"
      - dependency-name: "html-react-parser"
      - dependency-name: "html-to-image"
      - dependency-name: "jwt-decode"
      - dependency-name: "localforage"
      - dependency-name: "lodash"
      - dependency-name: "match-sorter"
      - dependency-name: "prop-types"
      - dependency-name: "react"
      - dependency-name: "react-ace"
      - dependency-name: "react-color"
      - dependency-name: "react-dom"
      - dependency-name: "react-hook-form"
      - dependency-name: "react-icons"
      - dependency-name: "react-markdown"
      - dependency-name: "react-redux"
      - dependency-name: "react-router-dom"
      - dependency-name: "react-toastify"
      - dependency-name: "rehype-sanitize"
      - dependency-name: "sort-by"
      - dependency-name: "use-debounce"
      - dependency-name: "uuid"
      - dependency-name: "zod"
      - dependency-name: "@types/dompurify"
      - dependency-name: "@types/node"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      - dependency-name: "@types/react-redux"
      - dependency-name: "@types/uuid"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "@vitejs/plugin-react"
      - dependency-name: "eslint"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-plugin-react-hooks"
      - dependency-name: "eslint-plugin-react-refresh"
      - dependency-name: "gh-pages"
      - dependency-name: "prettier"
      - dependency-name: "typescript"
      - dependency-name: "vite"
