sonar.projectKey=satya00089_landing-zone-orchestrator-ui
sonar.organization=satya00089

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-ssr/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/coverage/**

sonar.sourceEncoding=UTF-8
