import { library } from "@fortawesome/fontawesome-svg-core";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faArrowRotateRight,
  faArrowUpRightFromSquare,
  faChevronLeft,
  faChevronRight,
  faCircleNodes,
  faClock,
  faCopy,
  faCube,
  faEye,
  faEyeSlash,
  faFileLines,
  faFire,
  faFloppyDisk,
  faHeart,
  faLayerGroup,
  faPen,
  faPlus,
  faSearch,
  faSignOutAlt,
  faSitemap,
  faSpinner,
  faTag,
  faTrash,
  faUpRightFromSquare,
  faUser,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

// Keep the legacy `arrow-up-right` string used by existing UI copy while
// registering only the equivalent external-link icon definition.
const faArrowUpRight = {
  ...faArrowUpRightFromSquare,
  iconName: "arrow-up-right",
} as IconDefinition;

library.add([
  faArrowLeft,
  faArrowRotateRight,
  faArrowUpRight,
  faArrowUpRightFromSquare,
  faChevronLeft,
  faChevronRight,
  faCircleNodes,
  faClock,
  faCopy,
  faCube,
  faEye,
  faEyeSlash,
  faFileLines,
  faFire,
  faFloppyDisk,
  faHeart,
  faLayerGroup,
  faPen,
  faPlus,
  faSearch,
  faSignOutAlt,
  faSitemap,
  faSpinner,
  faTag,
  faTrash,
  faUpRightFromSquare,
  faUser,
  faXmark,
] as IconDefinition[]);
